# Generated by Django 3.1.7 on 2021-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='architect_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(max_length=250)),
                ('pin', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=250)),
                ('descrp', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='architect_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('arch_id', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('descrp', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='plan_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_plan_id', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=150)),
                ('descrp', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='plan_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sales_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('arch_id', models.IntegerField()),
                ('commision', models.FloatField()),
                ('card', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=25)),
                ('cvv', models.CharField(max_length=25)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('arch_id', models.IntegerField()),
                ('requirments', models.CharField(max_length=250)),
                ('filepath', models.CharField(max_length=250)),
                ('remark', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('query', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
    ]
